global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']
    metrics_path: '/metrics'

  - job_name: 'account-service'
    static_configs:
      - targets: ['account-service:4001']
    metrics_path: '/metrics'

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:4002']
    metrics_path: '/metrics'

  - job_name: 'ledger-service'
    static_configs:
      - targets: ['ledger-service:4003']
    metrics_path: '/metrics'

  - job_name: 'fx-service'
    static_configs:
      - targets: ['fx-service:4004']
    metrics_path: '/metrics'

  - job_name: 'payroll-service'
    static_configs:
      - targets: ['payroll-service:4005']
    metrics_path: '/metrics'

  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:4006']
    metrics_path: '/metrics'
